[metadata]
name = elevation_mapping_cupy
version = 2.0.0
author = Your Name
author_email = your.email@example.com
description = Elevation mapping on GPU
license = MIT

[options]
packages = find:
install_requires =
    setuptools
zip_safe = true

[options.entry_points]
console_scripts =
    elevation_mapping_node = elevation_mapping_cupy.elevation_mapping_ros:main

[develop]
script_dir=$base/lib/elevation_mapping_cupy

[install]
install_scripts=$base/lib/elevation_mapping_cupy
